### ISSUE TITLE
Question: Convertible vs Mappable

### ISSUE THREAD

**Issue by trevor-e** [lyft/mapper#103]
The example in the README does not make this very clear. My first thought is that `Convertible` allows for inline value parsing with type completions from a JSON structure (hence accepting `Any`), whereas `Mappable` represents the logical JSON transformation to an entity in code, meaning a mappable type is just a bunch of convertibles. This lines up with what I see in `DefaultConvertible.swift`.

In the location example, why would you choose to make it `Convertible` instead of `Mappable`? They appear to be interchangeable in this case, but since `location` is a nested structure, rather than an inline value, my instinct would be to make it `Mappable`. Seems like I'm missing something here, thanks!

**Comment by keith** [comment]
The original plan for Mapper was to only have a `Mappable` protocol. The problem comes when you want to conform an existing class that you don't control `Mappable`. Here's an example:

```swift
import Foundation

public struct Mapper {}

public protocol Mappable {
    init(map: Mapper)
}

extension NSDate: Mappable {
    public convenience init(map: Mapper) {
        self.init()
    }
}
```

When you compile this you end up with this error:

```
/private/tmp/foo.swift:10:24: error: initializer requirement 'init(map:)' can only be satisfied by a `required` initializer in the definition of non-final class 'NSDate'
    public convenience init(map: Mapper) {
                       ^
```

And when you take it's suggestion, and change it to required, you end up with this error:

```
/private/tmp/foo.swift:10:21: error: designated initializer cannot be declared in an extension of 'NSDate'; did you mean this to be a convenience initializer?
    public required init(map: Mapper) {
                    ^
                    convenience
/private/tmp/foo.swift:10:21: error: 'required' initializer must be declared directly in class 'NSDate' (not in an extension)
    public required init(map: Mapper) {
           ~~~~~~~~ ^
/private/tmp/foo.swift:10:21: error: initializer requirement 'init(map:)' can only be satisfied by a `required` initializer in the definition of non-final class 'NSDate'
    public required init(map: Mapper) {
                    ^
```

As far as I know there's no way to resolve this for classes such as `NSDate` (which isn't the best example because of `Date` but would be the same with any other classes you didn't control as well) which you don't control.

The utility of `Convertible` comes with the benefit of the implementation of `Convertible` doesn't particularly know where its value comes from in your JSON. Take this as an example:

```swift
struct RideKind: Mappable {
    let rawValue: String

    init(map: Mapper) {
        rawValue = try map.from("ride_kind")
    }
}

struct Ride: Mappable {
    let rideKind: RideKind

    init(map: Mapper) {
        rideKind = try map.from("")
    }
}
```

If you have a struct `Ride` and it has a property of type `RideKind` which conforms to `Mappable`, and you receive this JSON:

```json
{
    "id": "123",
    "ride_kind": "lyft_line"
    "passengers": ...
}
```

Everything would be fine. Your nested `RideKind` struct would extracted correctly (`""` passes the original JSON). But then imagine you have another struct `ScheduledRide` which also needs a property of type `RideKind`:

```swift
struct ScheduledRide: Mappable {
    let rideKind: RideKind

    init(map: Mapper) {
        rideKind = try map.from("")
    }
}
```

But for the JSON of this type you receive:

```json
{
    "id": "123",
    "ride_type": "lyft_line"
    "scheduled_time": ...
}
```

Note that here, since the key is different from that required by `Ride`, the parsing of `RideKind` would fail.

To solve this you can use convertible. In this case you would make something that looked like this:

```swift
struct RideKind: Convertible {
    let rawValue: String

    static func fromMap(_ value: Any) throws -> Thing {
        guard let string = value as? String else {
            throw MapperError.convertibleError(value: value, type: String.self)
        }

        return RideKind(rawValue: string)
    }
}
```

And then you would parse your `ScheduledRide` like this:

```swift
struct ScheduledRide: Mappable {
    let rideKind: RideKind

    init(map: Mapper) {
        rideKind = try map.from("ride_type")
    }
}
```

As you can see, this moves the concern about how a `RideKind` is parsed to the top level object, instead of `RideKind` itself. Probably an even better example for this is a more generic type. As implementation details of Mapper, types such as `String` are defined as `Convertible`. In this case there would be no way to make them `Mappable` since you could never know from the `Mappable` initializer on `String` which field to read.

Let me know if any of this isn't clear!

**Comment by trevor-e** [comment]
Thanks for the write-up!

Unfortunately that is mostly what I already knew about `Convertible`. It makes sense that the key for `RideKind` can change depending on the usage, similar to how you could have `starting_time` and `ending_time` for `Date` usages. This is what I meant by "inline value parsing", sorry if that was not clear.

The example from the README is this:

```
extension CLLocationCoordinate2D: Convertible {
  public static func fromMap(_ value: Any) throws -> CLLocationCoordinate2D {
    guard let location = value as? NSDictionary,
      let latitude = location["lat"] as? Double,
      let longitude = location["lng"] as? Double else
      {
         throw MapperError.convertibleError(value: value, type: [String: Double].self)
      }

      return CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
  }
}
```

What I'm saying is that to me it makes more sense to be:

```
extension CLLocationCoordinate2D: Mappable {
    public init(map: Mapper) throws {
        let lat: Double = try map.from("lat")
        let lon: Double = try map.from("lon")
        self.init(latitude: lat, longitude: lon)
    }
}
```

And then parsed the same as before like `try location = map.from("location")`. `CLLocationCoordinate2D` is a compound value being parsed out of a nested dictionary which is why it feels better to stick with `Mappable` in this case. There's also no ugly guard class or manual error throwing.

**Comment by keith** [comment]
Agreed! We should choose a better type for the example!

**Comment by keith** [comment]
Feel free to submit a docs change here
