### ISSUE TITLE
Better support for deserializing to dictionaries

### ISSUE THREAD

**Issue by trevor-e** [lyft/mapper#104]
Hi! `Mapper` is mostly used for converting JSON to a single value or an array of values. The only dictionary deserialization function that I found was for the `[Convertible: Convertible]` case. I also saw a dictionary transformation available for converting an array of something to a dictionary.

There's plenty of other dictionary deserialization cases that we use heavily in our app, such as `[Convertible: Mappable]`, `[Convertible: [Mappable]]`, and even `[Convertible: [Convertible]]`. For example, `[String: [String]]` or `[String: MyMappable]`.

I'm wondering if support for this type of deserialization is already in the works, or if it's something I should cook up myself and submit as a PR if you think it's a good idea. I was able to work around the `[Convertible: Mappable]` case with a transformation that looks like:

```
extension Transform {
    public static func toDictionary<Key, Value: Mappable>() -> (_ object: Any) throws -> [Key: Value]
        where Key: Hashable, Key: Convertible, Key.ConvertedType == Key
    {
        return { object in
            guard let objects = object as? [AnyHashable: [String: Any]] else {
                throw MapperError.convertibleError(value: object, type: [AnyHashable: [String: Any]].self)
            }

            var dictionary: [Key: Value] = [:]
            for (key, value) in objects {
                let convertedKey = try Key.fromMap(key)
                let model = try Value(map: Mapper(JSON: value as NSDictionary))
                dictionary[convertedKey] = model
            }

            return dictionary
        }
    }
}
```

However, it feels weird to do this as a transformation since this seems like a standard deserialization. It looks like I can't solve the array cases without modifying `Mapper` itself anyway which makes me think this should all live inside it.

As an aside, should `Mapper` work with extensions? I tried adding the dictionary functions via extension but several of the JSON helpers were not accessible, so I'll have to maintain a fork of this project in the meantime.

**Comment by keith** [comment]
I'm open to a solution for this problem. I think in our cases we've mostly solved this by adding more model objects, even if they're only used in the deserialization process. I kind of like the way we've done that because like you said, there's an infinite amount of cases we could want to support (if we started supporting even more nested cases as well, which realistically we probably wouldn't). If we could solve this in a more generic way that would work for multiple types with a single implementation, I would be more keen on adding support for it.

Feel free to submit an example PR that we can iterate on if you'd like.

> As an aside, should Mapper work with extensions? I tried adding the dictionary functions via extension but several of the JSON helpers were not accessible, so I'll have to maintain a fork of this project in the meantime.

Feel free to submit another issue with this with an example, I'm not exactly sure what's failing here
