### ISSUE TITLE
optionalFrom vs try?

### ISSUE THREAD

**Issue by Noobish1** [lyft/mapper#11]
Just a question, I may be missing something obvious but what is the benefit of the `optionalFrom` functions instead of the built in `try?`, I realise that the optionalFrom methods essentially just do that.

**Comment by keith** [comment]
Fair point. I prefer the decreased amount of syntax with `.optionalFrom` over `try? map.from("foo")` but that's just a personal preference. If you'd like to use `try?` everywhere that seems totally reasonable! :smile:

**Comment by osrl** [comment]
```
foo = map.optionalFrom("foo")
foo = try? map.from("foo")
bar = try  map.from("bar")
```
I think second line is shorter :) And looks more consistent with the third.
Just a suggestion: Since Swift has a dedicated syntax for this and fixed the memory leak on 2.2.1, I would remove the `optionalFrom(field: String)` and rename `optionalFrom(fields: [String])` to something more explanatory like `findFrom(fields:[String])` (or a better one).

**Comment by keith** [comment]
The second line is shorter, and definitely more consistent with `try map.from`. We'll think about doing this in the future. Thanks for the input!

**Comment by osrl** [comment]
I think this issue might be open again.

**Comment by Noobish1** [comment]
@osrl have a look at #83, it provides the explanation as to why optionalFrom exists.

**Comment by keith** [comment]
If we had the operator precedence mentioned in #83 we would totally remove optionalFrom
