### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by Austinate** [lyft/mapper#16]
Would you like to bring this feature.? 
I'd like to have one and can help with that if you think that is needed.

**Comment by keith** [comment]
We definitely want this. If you'd like to contribute it that'd be great! We need a way to test this once we do it. Along with this I'd like to run the tests on Linux. Which might be a separate thing but we should do that too.

**Comment by keith** [comment]
If you can figure out how to run the open source version of xctest, which looks like will require some test additions. That would be great. I've just spent a few minutes and looked into this and it's totally non obvious to me how to actually run tests with the new framework. And there doesn't seem to be much related documentation yet.

**Comment by Austinate** [comment]
I'll try figure out what we need to implement this.

**Comment by keith** [comment]
Spent some more time on this. I think that just getting it to build will be relatively easy. But long term (unless someone is waiting on swiftpm support) we may want to wait for https://github.com/apple/swift-evolution/pull/51 to be resolved and implemented before spending too much time on this.

**Comment by Austinate** [comment]
Agree that we probably should wait for testing support implementation at swiftpm.

**Comment by keith** [comment]
If we do start on this earlier we could start by creating a travis build on linux that at least does `swift build`. We could use [`swiftenv`](https://github.com/kylef/swiftenv) to help.

**Comment by Austinate** [comment]
Haven't seen swiftenv before, thanks for a link :+1:

**Comment by keith** [comment]
I've added swift pm support, and a build on OS X https://github.com/lyft/mapper/pull/22. Holding off on Linux support because of the first issue mentioned [here](https://github.com/apple/swift-corelibs-foundation/blob/master/Docs/Issues.md). Currently you cannot do `"foo" as? NSString`. Since `as?` Is a huge portion of how Mapper (currently) works, it's would be pretty useless to configure for linux, since it can't actually be used. I do have a branch for it, hoping everything gets fixed soon! https://github.com/lyft/mapper/tree/ks/swiftpm
