### ISSUE TITLE
How to handle Date

### ISSUE THREAD

**Issue by jbarros35** [lyft/mapper#162]
I have a class like that

 public init(map: Mapper) throws {
      do {
        try id = map.from("id")
        try firstName = map.from("firstName")
        try lastName = map.from("lastName")
        try pin = map.from("pin")
        try fullName = map.from("fullName")
        try active = map.from("active")
        try revokePin = map.from("revokePin")
        try gender = map.from("gender")
        try accountId = map.from("accountId")
        try contactNumber = map.from("contactNumber")
        //try birthDate = map.optionalFrom("birthDate")
      } catch {
          throw error
      }
    }

birthDate is a Date?, how to map? 
the framework gives me an error
birthDate = map.optionalFrom("birthDate")

Ambiguous reference to instance method 'optionalFrom'

**Comment by sunshinejr** [comment]
@jbarros35 I think you would probably need to map to a String first (or Int, depending on how the date is returned from your API) and then convert it to a date.

**Comment by keith** [comment]
Likely what you want to do here is define your own custom `Convertible` conformance for `Date`. As @sunshinejr alluded to the reason we don't provide one of these is because it depends on how the APIs you're interacting with send this data. Here's an example from our codebase:

```swift
import Foundation
import Mapper

extension Date: Convertible {
    public static func fromMap(_ value: Any) throws -> Date {
        if let string = value as? String, let date = self.fromStandardString(string) {
            return date
        }

        throw MapperError.convertibleError(value: value, type: String.self)
    }
}
```

Where `fromStandardString` is our custom handler that uses a `DateFormatter` with a custom `dateFormat` that our API sends. If this doesn't work for you please let me know!
