### ISSUE TITLE
error converting dictionary values

### ISSUE THREAD

**Issue by JohnCoates** [lyft/mapper#54]
Great library!

I tried to convert a dictionary and got this error:
```swift
UpdateResponse error: TypeMismatchError("users", [greg: {
    name = greg;
}], Swift.Dictionary<Swift.String, Swift.Dictionary<Swift.String, FlexApp.User>>)
```

Here's some sample code to reproduce the error:
```swift
struct User: Mappable {
    let name:String
    
    init(map: Mapper) throws {
        try name = map.from("name")
    }
}

struct UserList: Mappable {
    let users:[String:[String:User]]
    
    init(map: Mapper) throws {
        do {
            try users = map.from("users")
        }
        catch let error {
            print("UpdateResponse error: \(error)")
            throw error
        }
    }
}

 let JSON = [
            "users": [
                "greg": [ "name" : "greg"]
            ]
        ]
let userList = UserList.from(JSON)
print("user list: ", userList)
let user = User.from(JSON["users"]!["greg"]!)
print("user: ", user)

```

**Comment by keith** [comment]
Thanks!

So the problem here is something that will be solved by some variation of https://github.com/lyft/mapper/pull/7

The problem here is that at the base level we're just doing `foo as? [String: [String: User]]` which doesn't work, but it still compiles. What you'll want to do here is probably a `[String: NSDictionary]`, and then map over that to get the second dictionary.

**Comment by keith** [comment]
Closing this, feel free to reopen this if there's still an issue here. I've merged https://github.com/lyft/mapper/pull/59 so you should get a compile time error for anything that would fail at runtime as soon as I create a new release. If you find that isn't the case please open an issue!
