### ISSUE TITLE
Question: Is there any good patterns to avoid this common developer error?

### ISSUE THREAD

**Issue by Noobish1** [lyft/mapper#56]
So we've run into a few bugs where we're doing this:

1. A Model, `Model.swift` is created with a bunch of required properties (non-optional)
2. One of those properties is changed to be optional but the developer forgets to update the init method from `.from` to `.optionalFrom` and when we actually get a nil it crashes.

This can obviously be found with unit tests but is there any other ways of catching this?

**Comment by keith** [comment]
Hmm. I'm not sure I understand what you're thinking Mapper could do to help out in this situation. Without having a test covering these cases, and without knowledge of your JSON, I don't think we could do much to help this case.

When you say "it crashes" I guess if you mean that you're doing `Model.from(JSON)!` or `try!`, you could be handling those cases in a more graceful way, so they will fail with a user error, or at least without crashing your app.

Feel free to elaborate if I'm missing something!

**Comment by Noobish1** [comment]
So initially the model is like this:

```
internal struct Model: Mappable {
    internal let property: String
    
    internal init(map: Mapper) throws {
        try self.property = map.from("property")
    }
}
```

and then we change it to `property` to be optional:
```
internal struct Model: Mappable {
    internal let property: String?
    
    internal init(map: Mapper) throws {
        try self.property = map.from("property")
    }
}
```

but the developer forgets to update the `init` method so if we don't get a `property` in our JSON it throws an error. I realise this can't be a compile time error because you can always set a non-optional to an optional property, I was just wondering if you do anything to prevent this in your codebase.

**Comment by keith** [comment]
Ah interesting. Right I guess this is because of how swift allows you to assign `String` to `Optional<String>` where some other languages with similar type systems (haskell) would force you to be explicit about this.

One other problem with trying to figure out a way to fix this is your second case isn't particularly invalid. It is for the one Mapper initializer, but you could also have:

```swift
extension Model {
    init() {
        property = nil
    }
}
```

Which might not make much sense in this case, but once you have a few more properties it could.

We haven't really hit this problem in our codebase, partially because we use `optionalFrom` in a ton of places because of how our API works, and partially because our models rarely change after they're shipped.

**Comment by Noobish1** [comment]
Ok, thanks for the response all the same, hopefully we don't hit this too much and swift adds something to something like Haskell does.

Interestingly there's a similar kind of issue with the `??` operator where the left side doesn't have to be optional because it's defined as `T?`. I asked Joe Groff about it and he said: 
> "We're experimenting with language-level ways to limit the scope of optional-conversion behavior too."

**Comment by keith** [comment]
Ah that's interesting to hear, we've noticed code around like that before where we have `String ?? String` and it leads to a lot of confusion.

**Comment by keith** [comment]
Well if you can think of a great way for us to handle this on the Mapper side feel free to reopen this, closing for now!
