### ISSUE TITLE
Release 2.1.1

### ISSUE THREAD

**Issue by tomaskraina** [lyft/mapper#58]
Would be awesome if you could release a minor version containing this commit: https://github.com/lyft/mapper/commit/4f74320f9cef98fb98c7c8fcad6d45f8b293c337 (Make transformations throw MissingFieldErrors)

Cheers!

**Comment by keith** [comment]
Since this is a breaking change this will have to be a more major version number bump, which is why I've been putting it off. I was hoping to merge my `ks/compile-time` branch and then cut this major release. Let me see if that's feasible to do ASAP, otherwise I'll bite the bullet and we'll have to bump it twice.

**Comment by keith** [comment]
I've put a PR up for the other changes I wanted to make in to this major release here: https://github.com/lyft/mapper/pull/59

**Comment by keith** [comment]
I've just tagged version 3.0.0 and pushed it to CocoaPods. This should be an easy migration but it did have some breaking changes, see the CHANGELOG for details, or feel free to open an issue with any questions. Thanks!

**Comment by tomaskraina** [comment]
Thanks!
