### ISSUE TITLE
How to handle empty string to url transformations

### ISSUE THREAD

**Issue by rlam3** [lyft/mapper#96]
Would love to hear what is a better approach in handling empty string to url transformations. Thanks.

``` swift
    static func stringToURL(object: Any) throws -> URL {
        
        guard let string = object as? String else {
            throw MapperError.convertibleError(value: object, type: String.self)
        }
        
        // If string exists
        if string.isNotEmpty{
            return URL(string: string)!
        }else{
            return URL(string: "")! // ERRORS HERE BECAUSE STRING IS EMPTY AND IT IS TRYING TO UNWRAP THIS
        }
        
    }
```

**Comment by keith** [comment]
In the case that you have an empty string, what would your expected output be? Actually until Swift 3, creating a URL with an empty string returned a non-nil string. But regardless if nothing else you'd be better off changing your logic to throw instead of crash, and then handle that from your model in the case you expected a URL but didn't get one. Something like:

```swift
if let url = URL(string: string) {
    return url
} else {
    throw MapperError.convertibleError(value: object, type: URL.self)
}
```

Let me know if you have any other questions! Also note that Mapper has this functionality built in, so you can already map a string to a URL without any added code, see that implementation here: https://github.com/lyft/mapper/blob/master/Sources/NSURL+Convertible.swift#L13-L23

**Comment by rlam3** [comment]
@keith Thanks for the pointer!
